#!/bin/sh

if git config --get remote.origin.url | grep --quiet -F ssh://git@github.com/hioki; then
    exit 0
fi

COMMAND_TYPE=push
TARGET_BRANCHES="main master develop staging production"

current_branch="$(git symbolic-ref HEAD 2>/dev/null | sed -e 's/refs\/heads\///g')" || \
    current_branch="$(git describe --contains --all HEAD)"

if [ -z "${current_branch}" ]; then
    echo "Fix the bug in the $0 file because it failed to get the current branch"
    exit 2
fi

for target_branch in ${TARGET_BRANCHES}; do
    if [ "${current_branch}" = "${target_branch}" ]; then
        printf "Do not %s directly to the \033[31m%s\033[0m branch!\n" "${COMMAND_TYPE}" "${target_branch}"
        echo "(You can ignore this by \`$ git ${COMMAND_TYPE} --no-verify ...\`)"
        exit 1
    fi
done
